"""
Impact Analysis Service — per-spec-type KG traversal that creates
IMPACTS_* relationships (aligned with newEventLayer.py reference) and
returns a categorised impact report.

Relationship types match the reference exactly:
  Spec-layer:      IMPACTS_WORKSTEP_SPEC, IMPACTS_PART_SPEC,
                   IMPACTS_EQUIPMENT_SPEC, IMPACTS_OPERATION_SPEC,
                   IMPACTS_SPECIFICATION (generic fallback)
  Execution-layer: IMPACTS_PROCESS, IMPACTS_TASK,
                   IMPACTS_ORDER, IMPACTS_INVENTORY,
                   IMPACTS_VEHICLE, IMPACTS_PART_INSTANCE,
                   IMPACTS_EQUIPMENT_INSTANCE

Signature:
    run(change_action_id, spec_identifier, spec_type) -> dict
"""
from datetime import datetime
from services.neo4j_service import run_cypher


def _now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# ── Relationship creators ─────────────────────────────────────────────────────

def _impact_rel(ca_id: str, node_id: str, node_label: str, rel_type: str,
                severity: str, impact_type: str = "DIRECT", hold: bool = False):
    """Create an IMPACTS_* relationship on the ChangeAction."""
    run_cypher(
        f"MATCH (ca:ChangeAction {{identifier: $ca_id}}), "
        f"(n:{node_label} {{identifier: $node_id}}) "
        f"MERGE (ca)-[r:{rel_type}]->(n) "
        f"SET r.severity = $severity, r.impactType = $impact_type, "
        f"r.holdRequired = $hold, r.resolved = false, "
        f"r.reason = 'auto-generated by impact analysis'",
        {
            "ca_id": ca_id, "node_id": node_id,
            "severity": severity, "impact_type": impact_type, "hold": hold,
        },
    )


def _impact_spec_generic(ca_id, node_id, severity, impact_type="DIRECT"):
    _impact_rel(ca_id, node_id, "Specification", "IMPACTS_SPECIFICATION",
                severity, impact_type)


def _impact_workstep(ca_id, node_id, severity="HIGH"):
    _impact_rel(ca_id, node_id, "WorkStepSpec", "IMPACTS_WORKSTEP_SPEC", severity)


def _impact_part(ca_id, node_id, severity="HIGH"):
    _impact_rel(ca_id, node_id, "PartSpec", "IMPACTS_PART_SPEC", severity)


def _impact_equip(ca_id, node_id, severity="MEDIUM"):
    _impact_rel(ca_id, node_id, "EquipmentSpec", "IMPACTS_EQUIPMENT_SPEC", severity)


def _impact_operation(ca_id, node_id, severity="HIGH"):
    _impact_rel(ca_id, node_id, "OperationSpec", "IMPACTS_OPERATION_SPEC", severity)


def _impact_process(ca_id, node_id, severity="HIGH", hold=False):
    _impact_rel(ca_id, node_id, "ProductionProcess", "IMPACTS_PROCESS",
                severity, hold=hold)


def _impact_task(ca_id, node_id, severity="HIGH"):
    _impact_rel(ca_id, node_id, "OperationalTask", "IMPACTS_TASK", severity)


def _impact_order(ca_id, node_id, severity="HIGH", hold=True):
    _impact_rel(ca_id, node_id, "ProductionOrder", "IMPACTS_ORDER",
                severity, hold=hold)


def _impact_inventory(ca_id, node_id, severity="MEDIUM"):
    _impact_rel(ca_id, node_id, "InventoryRecord", "IMPACTS_INVENTORY", severity)


def _impact_vehicle(ca_id, node_id, severity="MEDIUM"):
    _impact_rel(ca_id, node_id, "Vehicle", "IMPACTS_VEHICLE", severity)


# ── Per-type traversal helpers ────────────────────────────────────────────────

def _traverse_part_spec(ca_id: str, spec_id: str, report: dict):
    """PartSpec → operations, inventory, production orders, processes."""
    # Operations requiring this part
    ops = run_cypher(
        "MATCH (op:OperationSpec)-[:REQUIRES_PART|requiresPart]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT op.identifier AS id",
        {"sid": spec_id},
    )
    for row in ops:
        oid = row.get("id")
        if oid:
            report["affected_operations"].append({"identifier": oid, "severity": "HIGH"})
            _impact_operation(ca_id, oid, "HIGH")

    # Inventory records
    inv = run_cypher(
        "MATCH (ir:InventoryRecord)-[:tracksSpec|TRACKS_SPEC|tracksPartSpec]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT ir.identifier AS id",
        {"sid": spec_id},
    )
    for row in inv:
        iid = row.get("id")
        if iid:
            report["affected_inventory"].append({"identifier": iid, "severity": "MEDIUM"})
            _impact_inventory(ca_id, iid, "MEDIUM")

    # Production orders that use this part
    orders = run_cypher(
        "MATCH (po:ProductionOrder)-[:REQUIRES_PART|requiresPart]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT po.identifier AS id",
        {"sid": spec_id},
    )
    for row in orders:
        oid = row.get("id")
        if oid:
            report["affected_orders"].append({"identifier": oid, "severity": "HIGH"})
            _impact_order(ca_id, oid, "HIGH", hold=True)

    # Processes via operations
    procs = run_cypher(
        "MATCH (pp:ProductionProcess)-[:hasTask|HAS_TASK]->(:OperationalTask)"
        "-[:realizesOperation|REALIZES_OPERATION]->(op:Operation)"
        "-[:REQUIRES_PART|requiresPart]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT pp.identifier AS id",
        {"sid": spec_id},
    )
    for row in procs:
        pid = row.get("id")
        if pid:
            report["affected_processes"].append({"identifier": pid, "severity": "HIGH"})
            _impact_process(ca_id, pid, "HIGH", hold=True)


def _traverse_equipment_spec(ca_id: str, spec_id: str, report: dict):
    """EquipmentSpec → work cells, operations, processes."""
    cells = run_cypher(
        "MATCH (wc:WorkCell)-[:HAS_EQUIPMENT|usesEquipment]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT wc.identifier AS id",
        {"sid": spec_id},
    )
    for row in cells:
        cid = row.get("id")
        if cid:
            report["affected_work_cells"].append({"identifier": cid, "severity": "HIGH"})

    ops = run_cypher(
        "MATCH (op:OperationSpec)-[:REQUIRES_EQUIPMENT|requiresEquipment]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT op.identifier AS id",
        {"sid": spec_id},
    )
    for row in ops:
        oid = row.get("id")
        if oid:
            report["affected_operations"].append({"identifier": oid, "severity": "HIGH"})
            _impact_operation(ca_id, oid, "HIGH")

    procs = run_cypher(
        "MATCH (pp:ProductionProcess)-[:operatesIn|OPERATES_IN]->"
        "(wc:WorkCell)-[:HAS_EQUIPMENT|usesEquipment]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT pp.identifier AS id",
        {"sid": spec_id},
    )
    for row in procs:
        pid = row.get("id")
        if pid:
            report["affected_processes"].append({"identifier": pid, "severity": "MEDIUM"})
            _impact_process(ca_id, pid, "MEDIUM")


def _traverse_tool_spec(ca_id: str, spec_id: str, report: dict):
    """ManualToolSpec / PrecisionToolSpec → operations, processes."""
    ops = run_cypher(
        "MATCH (op:OperationSpec)-[:REQUIRES_TOOL|requiresTool]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT op.identifier AS id",
        {"sid": spec_id},
    )
    for row in ops:
        oid = row.get("id")
        if oid:
            report["affected_operations"].append({"identifier": oid, "severity": "HIGH"})
            _impact_operation(ca_id, oid, "HIGH")

    procs = run_cypher(
        "MATCH (pp:ProductionProcess)-[:hasTask|HAS_TASK]->(:OperationalTask)"
        "-[:realizesOperation|REALIZES_OPERATION]->(op:Operation)"
        "-[:REQUIRES_TOOL|requiresTool]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT pp.identifier AS id",
        {"sid": spec_id},
    )
    for row in procs:
        pid = row.get("id")
        if pid:
            report["affected_processes"].append({"identifier": pid, "severity": "HIGH"})
            _impact_process(ca_id, pid, "HIGH")


def _traverse_work_step_spec(ca_id: str, spec_id: str, report: dict):
    """WorkStepSpec → operations, tasks, processes."""
    ops = run_cypher(
        "MATCH (op:OperationSpec)-[:HAS_STEP|hasStep]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT op.identifier AS id",
        {"sid": spec_id},
    )
    for row in ops:
        oid = row.get("id")
        if oid:
            report["affected_operations"].append({"identifier": oid, "severity": "HIGH"})
            _impact_operation(ca_id, oid, "HIGH")

    tasks = run_cypher(
        "MATCH (t:OperationalTask)-[:HAS_STEP|hasStep]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT t.identifier AS id",
        {"sid": spec_id},
    )
    for row in tasks:
        tid = row.get("id")
        if tid:
            report["affected_tasks"].append({"identifier": tid, "severity": "HIGH"})
            _impact_task(ca_id, tid, "HIGH")

    procs = run_cypher(
        "MATCH (pp:ProductionProcess)-[:hasTask|HAS_TASK]->(t:OperationalTask)"
        "-[:HAS_STEP|hasStep]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT pp.identifier AS id",
        {"sid": spec_id},
    )
    for row in procs:
        pid = row.get("id")
        if pid:
            report["affected_processes"].append({"identifier": pid, "severity": "HIGH"})
            _impact_process(ca_id, pid, "HIGH")


def _traverse_operation_spec(ca_id: str, spec_id: str, report: dict):
    """OperationSpec → tasks, processes, work cells, variants, shops."""
    tasks = run_cypher(
        "MATCH (t:OperationalTask)-[:realizesOperation|REALIZES_OPERATION]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT t.identifier AS id",
        {"sid": spec_id},
    )
    task_ids = []
    for row in tasks:
        tid = row.get("id")
        if tid:
            task_ids.append(tid)
            report["affected_tasks"].append({"identifier": tid, "severity": "HIGH"})
            _impact_task(ca_id, tid, "HIGH")

    if task_ids:
        procs = run_cypher(
            "MATCH (pp:ProductionProcess)-[:hasTask|HAS_TASK]->(t:OperationalTask) "
            "WHERE t.identifier IN $task_ids "
            "RETURN DISTINCT pp.identifier AS id",
            {"task_ids": task_ids},
        )
        for row in procs:
            pid = row.get("id")
            if pid:
                report["affected_processes"].append({"identifier": pid, "severity": "HIGH"})
                _impact_process(ca_id, pid, "HIGH")

    cells = run_cypher(
        "MATCH (wc:WorkCell)-[:PERFORMS|performs]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT wc.identifier AS id",
        {"sid": spec_id},
    )
    for row in cells:
        cid = row.get("id")
        if cid:
            report["affected_work_cells"].append({"identifier": cid, "severity": "HIGH"})

    variants = run_cypher(
        "MATCH (vv:VehicleVariant)-[:HAS_OPERATION|hasOperation]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT vv.identifier AS id",
        {"sid": spec_id},
    )
    for row in variants:
        vid = row.get("id")
        if vid:
            report["affected_variants"].append({"identifier": vid, "severity": "MEDIUM"})
            _impact_vehicle(ca_id, vid, "MEDIUM")

    shops = run_cypher(
        "MATCH (sh:ProductionShop)-[:MANAGES|manages]->(wc:WorkCell)"
        "-[:PERFORMS|performs]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT sh.identifier AS id",
        {"sid": spec_id},
    )
    for row in shops:
        sid2 = row.get("id")
        if sid2:
            report["affected_shops"].append({"identifier": sid2, "severity": "MEDIUM"})


def _traverse_production_plan_spec(ca_id: str, spec_id: str, report: dict):
    """ProductionPlanSpec / ProductionOrderSpec → processes, orders, shops."""
    procs = run_cypher(
        "MATCH (pp:ProductionProcess)-[:basedOn|BASED_ON|followsPlan|FOLLOWS_PLAN]->"
        "(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT pp.identifier AS id",
        {"sid": spec_id},
    )
    for row in procs:
        pid = row.get("id")
        if pid:
            report["affected_processes"].append({"identifier": pid, "severity": "HIGH"})
            _impact_process(ca_id, pid, "HIGH")

    orders = run_cypher(
        "MATCH (po:ProductionOrder)-[:basedOn|BASED_ON]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT po.identifier AS id",
        {"sid": spec_id},
    )
    for row in orders:
        oid = row.get("id")
        if oid:
            report["affected_orders"].append({"identifier": oid, "severity": "HIGH"})
            _impact_order(ca_id, oid, "HIGH", hold=True)

    shops = run_cypher(
        "MATCH (sh:ProductionShop)<-[:locatedIn|LOCATED_IN]-(pp:ProductionProcess)"
        "-[:basedOn|BASED_ON]->(s:Specification {identifier: $sid}) "
        "RETURN DISTINCT sh.identifier AS id",
        {"sid": spec_id},
    )
    for row in shops:
        sid2 = row.get("id")
        if sid2:
            report["affected_shops"].append({"identifier": sid2, "severity": "MEDIUM"})


def _traverse_generic_depends_on(ca_id: str, spec_id: str, report: dict):
    """Generic fallback: traverse DEPENDS_ON up to 2 hops."""
    direct = run_cypher(
        "MATCH (dep:Specification)-[:DEPENDS_ON]->(s:Specification {identifier: $sid}) "
        "RETURN dep.identifier AS id, labels(dep) AS lbls",
        {"sid": spec_id},
    )
    for row in direct:
        did = row.get("id")
        if did:
            report["affected_specs"].append({"identifier": did, "severity": "HIGH"})
            _impact_spec_generic(ca_id, did, "HIGH", "DIRECT")

    indirect = run_cypher(
        "MATCH (dep:Specification)-[:DEPENDS_ON*2]->(s:Specification {identifier: $sid}) "
        "RETURN dep.identifier AS id",
        {"sid": spec_id},
    )
    for row in indirect:
        did = row.get("id")
        if did:
            report["affected_specs"].append({"identifier": did, "severity": "MEDIUM"})
            _impact_spec_generic(ca_id, did, "MEDIUM", "INDIRECT")


# ── Dispatch table ────────────────────────────────────────────────────────────

_DISPATCH = {
    "PartSpec":                      _traverse_part_spec,
    "EquipmentSpec":                 _traverse_equipment_spec,
    "RoboticEquipmentSpec":          _traverse_equipment_spec,
    "ProcessEquipmentSpec":          _traverse_equipment_spec,
    "DiagnosticEquipmentSpec":       _traverse_equipment_spec,
    "MaterialHandlingEquipmentSpec": _traverse_equipment_spec,
    "ManualToolSpec":                _traverse_tool_spec,
    "PrecisionToolSpec":             _traverse_tool_spec,
    "WorkStepSpec":                  _traverse_work_step_spec,
    "OperationSpec":                 _traverse_operation_spec,
    "ProductionPlanSpec":            _traverse_production_plan_spec,
    "ProductionOrderSpec":           _traverse_production_plan_spec,
}

# All IMPACTS_* relationship types (for graph queries)
ALL_IMPACT_RELS = "|".join([
    "IMPACTS_SPECIFICATION",
    "IMPACTS_WORKSTEP_SPEC", "IMPACTS_PART_SPEC",
    "IMPACTS_EQUIPMENT_SPEC", "IMPACTS_OPERATION_SPEC",
    "IMPACTS_PROCESS", "IMPACTS_TASK",
    "IMPACTS_PART_INSTANCE", "IMPACTS_EQUIPMENT_INSTANCE",
    "IMPACTS_ORDER", "IMPACTS_VEHICLE", "IMPACTS_INVENTORY",
    "IMPACTS_ROLE",
])


# ── Public interface ──────────────────────────────────────────────────────────

def run(
    change_action_id: str,
    spec_identifier: str,
    spec_type: str,
) -> dict:
    """
    Traverse the KG from `spec_identifier` based on its `spec_type`,
    create IMPACTS_* relationships on the ChangeAction, and return a
    categorised impact report.
    """
    report: dict = {
        "change_action_id": change_action_id,
        "spec_type": spec_type,
        "affected_specs": [],
        "affected_operations": [],
        "affected_processes": [],
        "affected_tasks": [],
        "affected_work_cells": [],
        "affected_variants": [],
        "affected_shops": [],
        "affected_orders": [],
        "affected_inventory": [],
    }

    # Per-type traversal
    fn = _DISPATCH.get(spec_type)
    if fn:
        try:
            fn(change_action_id, spec_identifier, report)
        except Exception:
            pass

    # Always run generic DEPENDS_ON pass as well
    try:
        _traverse_generic_depends_on(change_action_id, spec_identifier, report)
    except Exception:
        pass

    # De-duplicate all lists by identifier
    for key, items in report.items():
        if isinstance(items, list) and items and isinstance(items[0], dict):
            seen: set = set()
            deduped = []
            for item in items:
                iid = item.get("identifier")
                if iid and iid not in seen:
                    seen.add(iid)
                    deduped.append(item)
            report[key] = deduped

    return report
